### PR TITLE
Add the Go API for a vertical separator

### PR DESCRIPTION
**Pull request by ajwillia-ms**
The API was in libui already, just updating the Go API.

fixes andlabs/ui#315

### CODE REVIEW

**Comment by andlabs** [comment]
I have this done locally. Thanks, however!

**Comment by ajwillia-ms** [comment]
Assuming that you have a lot more to put into the next upload of code would it be possible to merge this in the meantime?
I'm writing a tutorial and don't really want to explain that horizontal should be used in place of vertical.
Unless of course you're expecting the update to come in soon, in which case my apologies for the suggestion.

**Comment by andlabs** [comment]
Soon, yes.

Are you on macOS by any chance?

**Comment by ajwillia-ms** [comment]
I’m running on Linux, MacOS and trying to test on Windows too

**Comment by andlabs** [comment]
I ask this because on macOS there's a bug that causes horizontal separators to appear vertical under some conditions; see andlabs/libui#403.

**Pull request closed without merging**
