### PR TITLE
Rename static_windows_*.o files to .syso

### LINKED ISSUE #142: Run error on Windows 10
It shows error:
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

### PR DESCRIPTION
**Pull request by emersion**
`.syso` files are automatically included in the build by `go build`.

Fixes #142

### CODE REVIEW

**Comment by andlabs** [comment]
You should also rename libui_windows_*.res.o to .syso in this case. The only question is wil Go link these in the right order...

**Comment by emersion** [comment]
Why is renaming `libui_windows_*.res.o` files needed?

**Comment by andlabs** [comment]
Because those are also .o files. Actually, make that as a separate PR, please.

**Comment by emersion** [comment]
`.syso` files seems to be specifically for embedded `.rsrc` files...

**Comment by andlabs** [comment]
Yes, and the .res.o also contains rsrc resources, namely the dialog templates used by tab pages, the Font dialog, and the Color dialog. But again, we can test this on a separate PR. Thanks in the meantime!

**Comment by emersion** [comment]
Okay.

Also, `static_windows_386.syso` and `static_windows_amd64.syso` seems exactly the same file. Maybe we should keep only one?

**Comment by andlabs** [comment]
They do? Why are they not different architectures? (I do not know how object files on Windows work...)

**Comment by emersion** [comment]
Actually, they have exactly the same size, but they're not identical:
```
$ cmp -l static_windows_386.syso static_windows_amd64.syso | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
00000001 4C 64
00000002 01 86
00000014 01 00
00000505 07 03
```

**Pull request merged**
