### PR TITLE
OpenFile, SaveFile and MsgBox dialogs

### PR DESCRIPTION
**Pull request by pftbest**
Tested on OSX 10.11.5

### CODE REVIEW

**Comment by andlabs** [comment]
Are you sure `C.GoString(NULL) == ""`?

**Comment by pftbest** [comment]
No, I'm not sure, forgot to test it

**Comment by pftbest** [comment]
Yes it is, all works fine

**Comment by pftbest** [comment]
This is the relevant code from the runtime:
```Go
func gostring(p *byte) string {
	l := findnull(p)
	if l == 0 {
		return ""
	}
	s, b := rawstring(l)
	memmove(unsafe.Pointer(&b[0]), unsafe.Pointer(p), uintptr(l))
	return s
}

//go:nosplit
func findnull(s *byte) int {
	if s == nil {
		return 0
	}
	p := (*[_MaxMem/2 - 1]byte)(unsafe.Pointer(s))
	l := 0
	for p[l] != 0 {
		l++
	}
	return l
}
```

**Comment by pftbest** [comment]
Do I need to use C.uiFreeText instead of freestr ?

**Comment by andlabs** [comment]
For `uiOpen()`, yes.

**Comment by pftbest** [comment]
>For uiOpenFile() and uiSaveFile(), yes.

Already fixed that.

>I would suggest making the nil check explicit, just to be safe.

Found this in release notes for **2012-02-07**
`* cgo: accept null pointers in gccgo flavour of C.GoString (thanks Rémy Oudompheng),`
So this feature goes way back, even before go1

**Comment by pftbest** [comment]
They even use it in a standard library (`net/cgo_unix.go`):
```Go
func cgoLookupIPCNAME(name string) (addrs []IPAddr, cname string, err error, completed bool) {
// ...
	if res != nil {
		cname = C.GoString(res.ai_canonname)
		if cname == "" {
			cname = name
		}
		if len(cname) > 0 && cname[len(cname)-1] != '.' {
			cname += "."
		}
	}
// ...
}
```

**Comment by andlabs** [comment]
No issues in that case then. Thanks!

**Pull request merged**
