### PR TITLE
small change in the NewForeignEvent funktion.

### PR DESCRIPTION
**Pull request by s-gheldd**
Schould be doing now what it is supposed to do.

### CODE REVIEW

**Comment by andlabs** [comment]
What is this supposed to fix? I'm not entirely sure I follow.

I admit it's not documented (or at least not too well), but the value of `ForeignEvent.d` is the data received from the channel at the time of the event, not the channel itself. Check the implementation of `ForeignEvent.do()` immediately below. I forget what actually uses it, though...

**Comment by s-gheldd** [comment]
yes exactly. Before the fix the value in the channel was simply lost. Now its given to the handling function(as an inteface{}), which can then type assert and use it.

**Comment by andlabs** [comment]
Wait, are you saying the `fe.e.Recv()` in `do()` isn't actually removing the value from the channel?

**Comment by s-gheldd** [comment]
hmm actually you are right it should remove the value. Strange that it blocket the channel in my case.

Still it didnt give the value to the handlerfunction, because in line 142 you evaluate fe.d (which is the zero value because of zeroing in fe := &FereignEvent (...)).

The goroutine fe.do() fires after handler(fe.d) is evaluated. 

I stumbled upon it while writing a small chatclient, the setting of the text for incoming messages did not work. With the change its working solidly.

But I'm just a first year IT Student, who is working with go for a whole month now :D, so i could be dead wrong.

**Comment by andlabs** [comment]
That line is the line that's supposed to do the work of assigning the value received from the channel to `fe.d`. The `ui.Do()` immediately afterward will run your function with that as an argument and waits for the function to return. Is the argument to your function a nil value or something else that's obviously wrong? If there's a bug I'll fix it; I can also test it myself later.

**Comment by s-gheldd** [comment]
As i cant reproduce the bug. I want to apologize for wasting your time, and thank you for your effort.

**Comment by andlabs** [comment]
No worries. If you do get the bug again, let me know and I'll look into it.

**Pull request closed without merging**
